import type { ExerciseMeta } from '../types/exercises';

export const EXERCISES: Record<string, ExerciseMeta> = {
  reading_test: {
    id: 'reading_test',
    title: 'Test de Velocidad',
    category: 'Diagnóstico',
    mascot: 'swift',
    color: '#F97316',
    xp: 50,
    duration: '2 min',
    difficulty: 'Fácil',
    improves: 'Velocidad base',
    description: 'Mide tu velocidad natural de lectura (WPM) y comprensión base.',
    whyEffective: 'Para entrenar eficazmente, es crucial saber de dónde partes. Este test mide tu velocidad de lectura real y tu comprensión para configurar de manera óptima los ejercicios futuros.',
    steps: [
      'Lee el texto a tu ritmo natural de comprensión',
      'Presiona "Terminé de leer" al terminar',
      'Responde las preguntas de comprensión para validar el test',
    ],
  },
  focus_circle: {
    id: 'focus_circle',
    title: 'Círculo de Enfoque',
    category: 'Enfoque',
    mascot: 'focus',
    color: '#22C55E',
    xp: 40,
    duration: '1 min',
    difficulty: 'Fácil',
    improves: 'Foco y Atención',
    description: 'Entrena tu atención fija y visión periférica relajando la mente.',
    whyEffective: 'El foco es el pilar de la lectura. Al mantener tu mirada en un punto mientras el círculo crece, aumentas el control atencional, disminuyes la distracción externa y expandes tu visión periférica.',
    steps: [
      'Mira fijamente el punto blanco en el centro',
      'Sigue el ritmo de respiración en pantalla',
      'Nota la expansión del círculo sin desviar la mirada',
    ],
  },
  schulte: {
    id: 'schulte',
    title: 'Tabla de Schulte',
    category: 'Enfoque',
    mascot: 'focus',
    color: '#22C55E',
    xp: 40,
    duration: '2 min',
    difficulty: 'Fácil',
    improves: 'Campo visual',
    description: 'Entrena tu visión periférica. Encuentra los números del 1 al 25 sin mover los ojos.',
    whyEffective: 'Al obligar a tu cerebro a detectar números con la vista periférica, expandes el "tramo útil de fijación". Lectores rápidos capturan 3-5 palabras por golpe de vista; principiantes, solo 1-2. Este ejercicio ataca exactamente ese límite.',
    steps: [
      'Fija la mirada en el centro de la cuadrícula',
      'Localiza los números en orden ascendente',
      'Toca cada número tan rápido como puedas',
    ],
  },
  reading: {
    id: 'reading',
    title: 'Lectura Focal',
    category: 'Velocidad',
    mascot: 'swift',
    color: '#F97316',
    xp: 60,
    duration: '3 min',
    difficulty: 'Medio',
    improves: 'WPM',
    description: 'Swift te guiará palabra por palabra a la velocidad objetivo. Mantén la vista fija en el punto central.',
    whyEffective: 'La lectura tradicional pierde tiempo en regresiones y subvocalización. Al presentar una palabra a la vez en el mismo punto, eliminas el movimiento ocular y entrenas al cerebro a reconocer formas más rápido.',
    steps: [
      'Elige tu velocidad objetivo en WPM',
      'Mira el punto central, deja que las palabras pasen',
      'No regreses la vista — confía en el ritmo',
    ],
  },
  wordspan: {
    id: 'wordspan',
    title: 'Word Span',
    category: 'Memoria',
    mascot: 'calm',
    color: '#3B82F6',
    xp: 50,
    duration: '2 min',
    difficulty: 'Medio',
    improves: 'Memoria corta',
    description: 'Memoriza una secuencia de palabras y recupéralas en el mismo orden.',
    whyEffective: 'La memoria de trabajo es el cuello de botella de la lectura: si no retienes las palabras anteriores, pierdes el hilo del sentido. Ampliar tu span de palabras se traduce directamente en mejor comprensión.',
    steps: [
      'Observa cada palabra mientras se muestra',
      'Construye asociaciones mentales entre ellas',
      'Selecciónalas en el orden correcto',
    ],
  },
  loci: {
    id: 'loci',
    title: 'Método Loci',
    category: 'Memoria',
    mascot: 'loci',
    color: '#8B5CF6',
    xp: 70,
    duration: '4 min',
    difficulty: 'Difícil',
    improves: 'Memoria espacial',
    description: 'La técnica más poderosa: asocia objetos con habitaciones de una casa mental.',
    whyEffective: 'El cerebro evolucionó para recordar lugares, no listas. Anclar información en espacios familiares activa el hipocampo y crea recuerdos mucho más duraderos.',
    steps: [
      'Aprende qué objeto va en cada habitación',
      'Visualiza cada asociación vívidamente',
      'Recuerda dónde pusiste cada objeto',
    ],
  },
  comprehension: {
    id: 'comprehension',
    title: 'Comprensión Lectora',
    category: 'Comprensión',
    mascot: 'joy',
    color: '#EAB308',
    xp: 55,
    duration: '4 min',
    difficulty: 'Medio',
    improves: 'Comprensión',
    description: 'Lee un pasaje y responde preguntas para medir tu comprensión real.',
    whyEffective: 'Las preguntas después del texto te obligan a leer con propósito, identificar ideas clave y conectar detalles. Esa intención cambia cómo procesa tu cerebro.',
    steps: [
      'Lee el pasaje a tu ritmo natural',
      'Identifica ideas principales y detalles',
      'Responde preguntas sin volver al texto',
    ],
  },
  boss: {
    id: 'boss',
    title: 'Jefe de Zona',
    category: 'Evaluación',
    mascot: 'focus',
    color: '#DC2626',
    xp: 150,
    duration: '6 min',
    difficulty: 'Difícil',
    improves: 'Todo',
    description: 'Tres rondas de velocidad, memoria y comprensión. Derrota al jefe para desbloquear la siguiente zona.',
    whyEffective: 'Combinar varias habilidades bajo presión es lo que más se parece a leer en el mundo real: mantener la velocidad, recordar lo que ya leíste y comprender el todo.',
    steps: [
      'Ronda 1: velocidad — lee tan rápido como puedas',
      'Ronda 2: memoria — retén una secuencia',
      'Ronda 3: comprensión — responde correctamente',
    ],
  },
  freereading: {
    id: 'freereading',
    title: 'Lectura Libre',
    category: 'Comprensión',
    mascot: 'joy',
    color: '#22C55E',
    xp: 55,
    duration: '5 min',
    difficulty: 'Fácil',
    improves: 'Velocidad natural',
    description: 'Lee un pasaje a tu ritmo. Al terminar valida tu comprensión con un quiz.',
    whyEffective: 'La lectura libre sin presión de tiempo entrena el cerebro a procesar a su ritmo óptimo. El quiz posterior activa la lectura intencional — sabiendo que serás evaluado, tu atención aumenta automáticamente.',
    steps: [
      'Desplázate y lee el pasaje a tu ritmo',
      'Toca "Terminé" cuando acabes de leer',
      'Responde las preguntas sin volver al texto',
    ],
  },
};
